### ISSUE TITLE
subprocess.CalledProcessError: Command '['find', '/data/zotero_client_6/zotero-build/xpi/build/tmp/zotero/chrome/content/zotero/locale/csl', '-mindepth', '1', '!', '-name', '*.xml', '!', '-name', 'locales.json', '-print', '-delete']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by micrsun** [zotero/zotero-build#13]
root@docker:/data/zotero_client_6/zotero-standalone-build/scripts# ./dir_build -p w
Using source directory of /data/zotero_client_6/zotero-client/build
Deleting CSL locale support files
find: ‘/data/zotero_client_6/zotero-build/xpi/build/tmp/zotero/chrome/content/zotero/locale/csl’: No such file or directory

Traceback (most recent call last):
  File "/data/zotero_client_6/zotero-build/xpi/build_xpi", line 136, in main
    subprocess.check_call([
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['find', '/data/zotero_client_6/zotero-build/xpi/build/tmp/zotero/chrome/content/zotero/locale/csl', '-mindepth', '1', '!', '-name', '*.xml', '!', '-name', 'locales.json', '-print', '-delete']' returned non-zero exit status 1.
root@docker:/data/zotero_client_6/zotero-standalone-build/scripts#

**Comment by dstillman** [comment]
It looks like you didn't clone the submodules of zotero/zotero.

These are the instructions you need to follow:

https://www.zotero.org/support/dev/client_coding/building_the_standalone_client
