### ISSUE TITLE
"/data/zotero_client_6/zotero-build/xpi/build_xpi", line 148, in main

### ISSUE THREAD

**Issue by micrsun** [zotero/zotero-build#14]
root@docker:/data/zotero_client_6/zotero-standalone-build/scripts# ./dir_build -p w
Using source directory of /data/zotero_client_6/zotero-client/build
Deleting CSL locale support files

Traceback (most recent call last):
  File "/data/zotero_client_6/zotero-build/xpi/build_xpi", line 148, in main
    os.remove(os.path.join(tmp_src_dir, 'styles', 'update'))
FileNotFoundError: [Errno 2] No such file or directory: '/data/zotero_client_6/zotero-build/xpi/build/tmp/zotero/styles/update'

**Comment by dstillman** [comment]
It looks like you didn't clone the submodules of zotero/zotero.

These are the instructions you need to follow:

https://www.zotero.org/support/dev/client_coding/building_the_standalone_client
